name: Report code coverage

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate report
        run: ./gradlew clean test jacocoTestReport
      - uses: codecov/codecov-action@v1
        name: Upload report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/report.xml
          name: codecov-umbrella
          fail_ci_if_error: true
