name: Deploy Github Pages

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate document
        run: ./gradlew asciidoctor
      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_ACCESS_TOKEN }}
          BASE_BRANCH: develop
          BRANCH: gh-pages
          FOLDER: build/asciidoc/html5
